# nginx-rtmp配置文件
# 由PS5-Bilibili-Danmaku自动生成

worker_processes  1;
error_log  logs/error.log;
pid        logs/nginx.pid;

events {
    worker_connections  1024;
}

rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application app {
            live on;
            record off;
            interleave on;
        }
    }
}

http {
    server {
        listen 8080;
        location / {
            root html;
            index index.html;
        }

        location /stat {
            rtmp_stat all;
            rtmp_stat_stylesheet stat.xsl;
        }

        location /stat.xsl {
            root html;
        }

    }
}
